# Generated by Django 4.0 on 2021-12-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='custom_message',
            new_name='inner_message',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='message',
            new_name='outer_message',
        ),
    ]
