# Generated by Django 4.0 on 2021-12-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_custom_message_card_inner_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-date_created']},
        ),
    ]
