# Generated by Django 4.0 on 2021-12-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_card_inner_color_card_inner_font_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='inner_font',
        ),
        migrations.AddField(
            model_name='card',
            name='outer_image',
            field=models.URLField(null=True),
        ),
    ]
