# Generated by Django 4.0 on 2021-12-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_card_inner_font_card_outer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='inner_font',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
