# Generated by Django 4.0 on 2021-12-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_card_inner_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='inner_message',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='outer_message',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='recipient',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='sender',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
